language: java
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.m2
script: 
  - mvn -B package --file fridge-src/pom.xml -Dmaven.test.skip=true
after_success:
  - mkdir -p artifacts/
  - tar -zcvf artifacts/Fridge.tgz fridge-src/target/*.jar
  - echo "[Latest Build](Fridge.tgz)" > artifacts/index.md
deploy:
  provider: pages
  skip_cleanup: true
  token: $GH_token
  local_dir: artifacts/
  on:
    branch: main
